project:
  type: book
  output-dir: docs

book:
  title: "Melih Can Akgul Progress Journal"
  repo-url: https://github.com/pjournal/mef07-meakgul
  chapters:
    - index.qmd
    - assignment1.qmd
    - inClass1.qmd
    - assignment_shiny.qmd
    - operation_research_hw.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo

